pipeline {
    agent any
        stage('Run Tests') {
            steps {
                script {
                    sh '''
                        . venv/bin/activate
                        pytest ./'PyTest DQ Framework' -v --html=report.html
                    '''
                }
            }
        }
}
