pipeline {
    agent any
    stages {
        stage('Update Packages') {
            steps {
                script {
                    // Update the package list
                    sh 'apt-get update'
                    sh 'apt-get install -y libpq-dev'
                }
            }
        }
        stage('Install Python') {
            steps {
                // Install Python and pip
                sh 'apt-get install -y python3 python3-pip python3-venv'
            }
        }
        stage('Clone Repository') {
            steps {
                script {
                    // Clone the Git repository
                    git branch: 'main', url: 'https://github.com/namiup/dqe-automation/'
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    // Create a virtual environment
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install pytest
                        pip install -r data_dev/requirements.txt
                    '''
                }
            }
        }
        stage('Run main') {
            steps {
                script {
                    // Activate the virtual environment, set PYTHONPATH, and run the script
                    sh '''
                        . venv/bin/activate
                        export PYTHONPATH=$WORKSPACE
                        python data_dev/main.py
                    '''
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    sh '''
                        . venv/bin/activate
                        pytest --reportportal ./'PyTest Introduction' -v --html=report.html --file_path="./PyTest Introduction/src/data/data.csv" --actual_schema=id,name,age,email,is_active
                    '''
                }
            }
        }
        // stage('Run Results') {
        //     steps {
        //         junit 'results.xml'
        //     }
        // }
    }
    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs for details.'
        }
    }
}


