pipeline {
    agent any
    stages {
        stage('Start Selenium Chrome Container') {
            steps {
                sh '''
                    podman pull selenium/standalone-chrome:latest
                    podman run -d --name selenium-chrome -p 4444:4444 selenium/standalone-chrome:latest
                '''
            }
        }
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/namiup/dqe-automation/'
            }
        }
        stage('Install Python & Dependencies') {
            steps {
                sh '''
                    apt-get update
                    apt-get install -y python3 python3-pip python3-venv
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r 'Robot Framework'/requirements.txt
                '''
            }
        }
        stage('Run Tests') {
            steps {
                sh '''
                    . venv/bin/activate
                    robot --include smoke 'Robot Framework/test.robot'
                '''
            }
        }
        stage('Cleanup Selenium Container') {
            steps {
                sh '''
                    podman stop selenium-chrome || true
                    podman rm selenium-chrome || true
                '''
            }
        }
    }
    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs for details.'
        }
    }
}
