pipeline {
    agent any
    stages {
        stage('Install dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
}
        }
        stage('Run tests') {
            steps {
                sh 'pytest --maxfail=1 --disable-warnings --junitxml=results.xml'
}
        }
        stage('Archive Results') {
            steps {
                junit 'results.xml'
}
        }
    }
}
